# Generated by Django 3.2.8 on 2021-10-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateFromHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('uuid', models.IntegerField(verbose_name='Uuid')),
                ('date', models.DateTimeField(verbose_name='Date and Time')),
                ('staus', models.IntegerField(verbose_name='Status')),
                ('type_passage', models.IntegerField(verbose_name='Type Passage')),
                ('sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, verbose_name='Plate Number')),
                ('plate_number_datefromhub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datahub.datefromhub')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('photo_datefromhub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datahub.datefromhub')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, verbose_name='Group')),
                ('group_datefromhub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datahub.datefromhub')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50, verbose_name='Direction')),
                ('direction_datefromhub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datahub.datefromhub')),
            ],
        ),
    ]
