# Generated by Django 3.2.8 on 2021-10-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datefromhub',
            old_name='staus',
            new_name='status',
        ),
    ]
