# Generated by Django 3.2.8 on 2021-10-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_rename_staus_datefromhub_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platenumber',
            name='plate_number_datefromhub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pn', to='datahub.datefromhub'),
        ),
    ]
