# Generated by Django 3.2.8 on 2021-10-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_alter_platenumber_plate_number_datefromhub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platenumber',
            name='plate_number_datefromhub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platenumber', to='datahub.datefromhub'),
        ),
    ]
