# Generated by Django 3.2.8 on 2021-10-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_alter_platenumber_plate_number_datefromhub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateFromHub',
            new_name='DataFromHub',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='direction_datefromhub',
            new_name='direction_datafromhub',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_datefromhub',
            new_name='group_datafromhub',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_datefromhub',
            new_name='photo_datafromhub',
        ),
        migrations.RenameField(
            model_name='platenumber',
            old_name='plate_number_datefromhub',
            new_name='plate_number_datafromhub',
        ),
    ]
